(ns electron.db-schema)

;; TODO: how to keep this sync with frontend.db.schema?

(def schema [{:db/ident :block/uuid
              :db/valueType :db.type/uuid
              :db/cardinality :db.cardinality/one
              :db/unique :db.unique/identity }
             {:db/ident :block/parent
              :db/valueType :db.type/ref
              :db/cardinality :db.cardinality/one
              :db/index true}
             {:db/ident :block/left
              :db/valueType :db.type/ref
              :db/cardinality :db.cardinality/one
              :db/index true}
             {:db/ident :block/collapsed?
              :db/valueType :db.type/boolean
              :db/cardinality :db.cardinality/one
              :db/index true}
             {:db/ident :block/format
              :db/valueType :db.type/keyword
              :db/cardinality :db.cardinality/one}
             {:db/ident :block/page
              :db/valueType :db.type/ref
              :db/cardinality :db.cardinality/one
              :db/index true}
             {:db/ident :block/refs
              :db/valueType :db.type/ref
              :db/cardinality :db.cardinality/many}
             {:db/ident :block/path-refs
              :db/valueType :db.type/ref
              :db/cardinality :db.cardinality/many}
             {:db/ident :block/tags
              :db/valueType :db.type/ref
              :db/cardinality :db.cardinality/many}
             {:db/ident :block/alias
              :db/valueType :db.type/ref
              :db/cardinality :db.cardinality/many}
             {:db/ident :block/name
              :db/valueType :db.type/string
              :db/unique :db.unique/identity
              :db/cardinality :db.cardinality/one}
             {:db/ident :block/original-name
              :db/valueType :db.type/string
              :db/unique :db.unique/identity
              :db/cardinality :db.cardinality/one}
             {:db/ident :block/namespace
              :db/valueType :db.type/ref
              :db/cardinality :db.cardinality/one}
             {:db/ident :block/macros
              :db/valueType :db.type/ref
              :db/cardinality :db.cardinality/many}
             {:db/ident :block/file
              :db/valueType :db.type/ref
              :db/cardinality :db.cardinality/one}
             {:db/ident :file/path
              :db/valueType :db.type/string
              :db/cardinality :db.cardinality/one
              :db/unique :db.unique/identity}])
